Sign up page
GSG-FC02/Online-Learning-UI-Team-7 pull request #8
Opened 2021-03-19 23:15 UTC by ayaasqoul88

2021-03-20 04:50 UTC, emanjaber commented on css/index.css
> +  border-radius: 10px;
add this code to make the style better 
```
border: none;
outline: none;
```

2021-03-20 04:52 UTC, emanjaber commented on css/index.css
> +  border-radius: 10px;
add this code to make the style better 
```
border: none;
outline: none;
```

2021-03-20 04:53 UTC, emanjaber commented on css/index.css
> +  /* font-family: "DM Sans"; */
You can remove this comment

2021-03-20 05:05 UTC, emanjaber commented on css/index.css
> +.icon {
make it more specific, to avoid problems after that 
add parent class to it, like:
`.inputContainer .icon`

the same thing for `.input-field` and `.button`

2021-03-20 05:10 UTC, emanjaber commented on css/index.css
> +  font-size: 20px;
make the size bigger, I think `50px` is good enough

2021-03-20 05:17 UTC, emanjaber commented on css/index.css
> +  color: #1617196b;
add `font-size: 12px;` to make the style more similar to the original one

2021-03-20 05:18 UTC, emanjaber commented on index.html
> +        <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=DM+Sans"> -->
you can remove this comment

2021-03-20 05:21 UTC, emanjaber commented on index.html
> +<h1 class="header-title"> SINAU </h1>
use prettier, from View then Command Palette

2021-03-20 05:23 UTC, emanjaber requested changes
Good work Aya!

But there are some comments I wish you see them

2021-03-20 06:36 UTC, AbdallahGot commented
![image](https://user-images.githubusercontent.com/76267220/111861418-c6c62800-8956-11eb-91e5-f655e50fb60d.png)
very good , 
but try to solve this problem.

2021-03-20 06:38 UTC, AbdallahGot requested changes
![image](https://user-images.githubusercontent.com/76267220/111861509-9337cd80-8957-11eb-9d49-6f517df1b5bb.png)
very good,
but try to solve this problem

2021-03-20 11:20 UTC, emanjaber approved these changes
Perfect Aya

2021-03-20 11:38 UTC, AbdallahGot approved these changes

2021-03-21 05:10 UTC, emanjaber commented on index.html
> +            <button type="button" class="button Bone"> <a href="../Online-Learning-UI-Team-7/html/home.html">Sing In</a></button>
make it like this:
`<a href="../Online-Learning-UI-Team-7/html/home.html"><button type="button" class="button Bone"> Sing In</button></a>`

2021-03-21 05:15 UTC, emanjaber requested changes
edit this   `border-radius: 30px 30px 30px 30px;`
to   `border-radius: 30px 30px 0 0;`
in line 56 from css file

2021-03-22 13:52 UTC, merged